#!/bin/bash

echo "🚀 CliGool Windows客户端修复版本部署"
echo "========================================"
echo ""

echo "🔧 本次修复内容:"
echo "   ✅ 添加bufio.Writer确保输入立即flush"
echo "   ✅ 改进cmd.exe启动参数配置"
echo "   ✅ 增强调试日志显示详细信息"
echo ""

echo "📊 预期效果:"
echo "   当你在网页输入命令时，客户端会显示:"
echo "   - 📥 收到输入: xxx (长度: x)"
echo "   - ✅ 已写入 x 字节到stdin (缓冲)"
echo "   - ✅ 已flush输入缓冲区"
echo "   - 📤 从stdout读取 x 字节"
echo ""

echo "🌐 本地服务状态:"
docker ps | grep cligool
echo ""

echo "📍 本地下载页面:"
echo "   http://localhost:8081"
echo ""

echo "🔄 部署到远程服务器的步骤:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法1: 导出镜像并传输 (推荐)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  导出本地镜像:"
echo "   docker save cligool-relay-server | gzip > cligool-windows-fix.tar.gz"
echo ""
echo "2️⃣  传输到服务器:"
echo "   scp cligool-windows-fix.tar.gz your-server:/tmp/"
echo ""
echo "3️⃣  在服务器上加载镜像:"
echo "   ssh your-server"
echo "   docker load < /tmp/cligool-windows-fix.tar.gz"
echo "   cd /path/to/cligool"
echo "   docker-compose up -d --force-recreate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法2: 在服务器上重新构建 (需要代码)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  SSH登录到服务器"
echo "   ssh your-server"
echo ""
echo "2️⃣  进入项目目录并拉取最新代码"
echo "   cd /path/to/cligool"
echo "   git pull origin master"
echo ""
echo "3️⃣  重新构建并启动"
echo "   docker-compose build"
echo "   docker-compose up -d --force-recreate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ 部署完成后:"
echo "   1. 访问 https://cligool.zty8.cn"
echo "   2. 下载新的 cligool-windows-amd64.zip"
echo "   3. 解压并运行客户端"
echo "   4. 在网页终端中测试: dir"
echo "   5. 查看客户端日志，应该看到完整的输入/输出流程"
echo ""

echo "🧪 测试验证步骤:"
echo ""
echo "1. 启动Windows客户端，会话ID: xxx"
echo "2. 打开网页: https://cligool.zty8.cn/session/xxx"
echo "3. 在网页输入: dir"
echo "4. 预期输出:"
echo "   📥 收到输入: \"d\" (长度: 1)"
echo "   ✅ 已写入 1 字节到stdin (缓冲)"
echo "   ✅ 已flush输入缓冲区"
echo "   📥 收到输入: \"i\" (长度: 1)"
echo "   ✅ 已写入 1 字节到stdin (缓冲)"
echo "   ✅ 已flush输入缓冲区"
echo "   📥 收到输入: \"r\" (长度: 1)"
echo "   ✅ 已写入 1 字节到stdin (缓冲)"
echo "   ✅ 已flush输入缓冲区"
echo "   📥 收到输入: \"\\r\" (长度: 1)"
echo "   ✅ 已写入 1 字节到stdin (缓冲)"
echo "   ✅ 已flush输入缓冲区"
echo "   📤 从stdout读取 123 字节"
echo "   ✅ 已发送 123 字节到WebSocket"
echo "   [网页应该显示dir命令的输出]"
echo ""

echo "⚠️  如果仍然有问题:"
echo "   1. 确认下载了新的客户端"
echo "   2. 确认服务器已更新到最新版本"
echo "   3. 查看服务器日志: docker logs cligool-relay -f"
echo "   4. 查看客户端日志，确认每一步都有输出"
echo ""

echo "💡 核心改进:"
echo "   之前: stdin.Write()可能缓冲，cmd.exe无法及时收到输入"
echo "   现在: bufio.Writer + Flush()确保输入立即送达cmd.exe"
echo ""
