services:
  - type: web
    name: cligool-relay
    plan: free
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile.multiarch
    healthCheckPath: /api/health
    envVars:
      - key: RELAY_HOST
        value: 0.0.0.0
      - key: RELAY_PORT
        value: "8080"
