#!/bin/bash

echo "🚀 CliGool 远程服务器更新指南"
echo "======================================"
echo ""

echo "📋 当前状态:"
echo "   ✅ 本地代码已更新并提交"
git log --oneline -1

echo ""
echo "🌐 远程服务器: https://cligool.zty8.cn"
echo ""
echo "🔄 请按以下步骤更新远程服务器:"
echo ""

echo "方法1: SSH登录到服务器"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. SSH登录到您的服务器"
echo "   ssh your-server"
echo ""
echo "2. 进入项目目录"
echo "   cd /path/to/cligool"
echo ""
echo "3. 拉取最新代码"
echo "   git pull origin master"
echo ""
echo "4. 重新构建并启动"
echo "   docker-compose build"
echo "   docker-compose up -d"
echo ""
echo "5. 验证更新"
echo "   docker logs cligool-relay --tail 5"
echo ""

echo "方法2: 使用CI/CD自动部署 (如果配置了的话)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   git push origin master"
echo "   # 触发自动部署"
echo ""

echo "方法3: 手动传输文件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 重新构建本地镜像:"
echo "   docker-compose build"
echo ""
echo "2. 导出镜像:"
echo "   docker save cligool-relay-server | gzip > cligool-latest.tar.gz"
echo ""
echo "3. 传输到服务器并加载:"
echo "   scp cligool-latest.tar.gz your-server:/tmp/"
echo "   ssh your-server 'docker load < /tmp/cligool-latest.tar.gz'"
echo ""
echo "4. 在服务器上重启服务"
echo "   docker-compose up -d"
echo ""

echo "✅ 更新完成后:"
echo "   1. 清除浏览器缓存"
echo "   2. 重新下载Windows客户端"
echo "   3. 运行新客户端应该看到详细日志"
echo ""
echo "🎯 新版本特点:"
echo "   🚀 程序启动立即显示日志"
echo "   🔗 显示WebSocket连接步骤"
echo "   🖥️  显示cmd.exe启动和PID"
echo "   📥 显示输入接收情况"
echo "   📤 显示输出读取情况"
echo ""
echo "🧪 预期的客户端输出:"
echo "   🚀 CliGool Windows客户端启动..."
echo "   📋 会话ID: xxx"
echo "   🔗 开始连接WebSocket..."
echo "   📡 WebSocket URL: wss://..."
echo "   ✅ WebSocket已连接"
echo "   🔧 准备启动cmd.exe..."
echo "   ✅ cmd.exe已启动，PID: 1234"
